variables:
  resitry: cloud.docker.com
  image: xiliangma/restapi
#  tag: $CI_COMMIT_SHA
  tag: latest
  gopath: /go/src/github.com/xiliangMa
  deployFile: deploy-k8s.yml

stages:
  - build
  - publish
  - deploy

go-build:
  stage: build
  image: golang:1.11
  only:
    - dev
  script:
    - mkdir -p $gopath
    - ln -s `pwd` $gopath/restapi
    - cd $gopath/restapi
    - go build -o bin/restapi
  artifacts:
    paths:
      - bin
      - conf
      - swagger

buid-docker-image:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  only:
    - dev
  dependencies:
    - go-build
  script:
    #change your docker hub user name and pwd
    - docker login -u xiliangma -p maxiliang4115
    - docker build -t $image:$tag .
    - docker push $image:$tag
    - echo "build success $image:$tag"

#deploy-k8s:
#  stage: deploy
#  image: $image:$tag
#  script:
#    - cat $deployFile
#    - kubectl apply -f $deployFile