apiVersion: v1
kind: Service
metadata:
  name: restapi-mariadb
  labels:
    app: restapi-mariadb
spec:
  selector:
    app: restapi-mariadb
  ports:
  - name: dev
    port: 3306
    targetPort: mysql
