apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-resources-quota
  namespace: restapi
spec:
  hard:
    pods: 20
    requests.cpu: 1
    requests.memory: 1Gi
    limits.cpu: 40
    limits.memory: 5Gi